export const dashItems =  [
    { id: 1,
        title: 'Total Requests',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/totalRequests.png',
        num: 14,
    },
    { id: 2,
        title: 'Job Orders',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/jo.png',
        num: 5,
    },
    { id: 3,
        title: 'Maintenance',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/mechanic.png',
        num: 9,
    },
    { id: 4,
        title: 'Transfers',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/transfer.png',
        num: 15,
    },
    { id: 5,
        title: 'Issuance',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/issuance.png',
        num: 21,
    },
    { id: 6,
        title: 'Disposals',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/garbage.png',
        num: 10,
    },
    { id: 7,
        title: 'Lost Assets',
        link: '/systemSetup/user/userProfile',
        imgSrc: '/dashIcons/lost.png',
        num: 0,
    },
];
